### ISSUE TITLE
Regular Expression Matching(Python or cpp)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-programs-projects#107]
Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:

-  '.' Matches any single character.​​​​
-  '*' Matches zero or more of the preceding element.
The matching should cover the entire input string (not partial).

Example 1:

Input: s = "aa", p = "a"
Output: false
Explanation: "a" does not match the entire string "aa".

Example 2:

Input: s = "aa", p = "a*"
Output: true
Explanation: '*' means zero or more of the preceding element, 'a'. Therefore, by repeating 'a' once, it becomes "aa".

**Comment by 1-Sanchit-1** [comment]
can you please assgin me
