### ISSUE TITLE
Minimize the Heights II (python or cpp only)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-programs-projects#29]
Given an array arr[] denoting heights of N towers and a positive integer K.

For each tower, you must perform exactly one of the following operations exactly once.

Increase the height of the tower by K
Decrease the height of the tower by K
Find out the minimum possible difference between the height of the shortest and tallest towers after you have modified each tower.

You can find a slight modification of the problem [here](https://practice.geeksforgeeks.org/problems/minimize-the-heights-i/1/).
Note: It is compulsory to increase or decrease the height by K for each tower. After the operation, the resultant array should not contain any negative integers.

Example 1:
Input:
K = 2, N = 4
Arr[ ] = {1, 5, 8, 10}
Output:
5

Explanation:
The array can be modified as 
{3, 3, 6, 8}. The difference between 
the largest and the smallest is 8-3 = 5.

**Comment by Sougata2** [comment]
kindly assign this issue to me. Please
