### ISSUE TITLE
Zero Sum Subarrays (Python or cpp only)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-programs-projects#35]
You are given an array arr[] of size n. Find the total count of sub-arrays having their sum equal to 0.
Example 1:

Input:
n = 6
arr[] = {0,0,5,5,0,0}
Output: 6
Explanation: The 6 subarrays are 
[0], [0], [0], [0], [0,0], and [0,0].

Example 2:

Input:
n = 10
arr[ ] = {6,-1,-3,4,-2,2,4,6,-12,-7}
Output: 4
Explanation: The 4 subarrays are [-1 -3 4]
[-2 2], [2 4 6 -12], and [-1 -3 4 -2 2]

**Comment by cereal-hecker** [comment]
hey, pls assign this task to me

**Comment by vilasrhegde** [comment]
Hey @cereal-hecker can you assign me this? I would like to solve using Python

**Comment by vilasrhegde** [comment]
Hey @anomekumar08 can you assign me this? I'd like to solve using Python.

**Comment by vilasrhegde** [comment]
@anomekumar08 I wonder why can't we make subarray of [0,0,0] and [0,0,0,0] in example 1

**Comment by vilasrhegde** [comment]
@anomekumar08 I've solved this issue. Can you assign me this task?

**Comment by anomekumar08** [comment]
Ok
