### ISSUE TITLE
Overlapping Intervals(using python or cpp only)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-programs-projects#36]
Given a collection of Intervals, the task is to merge all of the overlapping Intervals.

Example 1:

Input:
Intervals = {{1,3},{2,4},{6,8},{9,10}}
Output: {{1, 4}, {6, 8}, {9, 10}}
Explanation: Given intervals: [1,3],[2,4] ,[6,8],[9,10], we have only two overlapping intervals here,[1,3] and [2,4]. Therefore
we will merge these two and return [1,4],[6,8], [9,10].

Example 2:

Input:
Intervals = {{6,8},{1,9},{2,4},{4,7}}
Output: {{1, 9}}

**Comment by botketan** [comment]
You can assign this to me

**Comment by omi-sha** [comment]
hi you can assign this to me i can implement it using c++
