### ISSUE TITLE
Search in a Rotated Array(python or cpp only)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-programs-projects#37]
Given a sorted and rotated array A of N distinct elements which is rotated at some point, and given an element key. The task is to find the index of the given element key in the array A.

Example 1:

Input:
N = 9
A[ ] = {5, 6, 7, 8, 9, 10, 1, 2, 3}
key = 10
Output:  5
Explanation: 10 is found at index 5.

Example 2:

Input:
N = 4
A[ ] = {3, 5, 1, 2}
key = 6
Output: -1
Explanation: There is no element that has value 6.

**Comment by jay13makhija** [comment]
Please assign me this issue. I have worked on it, will immediately send a pull request

**Comment by AryamanAdivyaSingh47** [comment]
Hello sir, Can you please assign this issue to me for hacktoberfest 2022. I would be thankful.

**Comment by RKSingh5** [comment]
please assign this to me

**Comment by MayankUghade** [comment]
**@anomekumar08 I would like to work for this, please assign me this task.**
