### ISSUE TITLE
Maximum subset XOR(python , cpp and java only)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-programs-projects#38]
Given an array arr[] of N positive integers. Find an integer denoting the maximum XOR subset value in the given array arr[].

Example 1:

Input : 
N = 3
arr[ ] = {2, 4, 5}
Output : 7
Explanation : The subset {2, 5} has maximum subset XOR value.

Example 2 :

Input : 
N= 3
arr[ ] = {9, 8, 5}
Output : 13
Explanation : The subset {8, 5} has maximum subset XOR value.

**Comment by Devesh-coder** [comment]
Hey, @anomekumar08 would like to solve this using java!

**Comment by vavy06** [comment]
Hey! I want to implement in C++. Please assign me.

**Comment by omi-sha** [comment]
hi please assign this to me , would like to write code in c++

**Comment by richie-6789** [comment]
Hey! I would like to solve this in Python.
